spring:
  application:
    name: cravocanela
  datasource:
    url: jdbc:postgresql://localhost:5432/cravocanela
    username: admin
    password: admin
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:/db/master.xml
    drop-first: false
  jackson:
    date-format: yyyy-MM-dd
    deserialization:
      fail-on-unknown-properties: false